import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import CLayout from "../components/CLayout";
import Backing from "../components/Backing";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CLayout>
                <Backing
                    style={{
                        textAlign: "center",
                        fontSize: "20pt",
                    }}
                >
                    <p>
                        Central Dashboard for everything the Tracker application
                        tracks.
                    </p>
                    <p>Click below to view dashboards</p>
                    <div>
                        <button>
                            {" "}
                            <Link
                                href="/nextWebsite"
                                style={{
                                    color: "black",
                                }}
                            >
                                nextWebsite
                            </Link>
                        </button>
                    </div>
                    <p>
                        This site also serves as a sandbox for me to try out
                        styling things
                    </p>
                </Backing>
            </CLayout>
        </>
    );
}
